### PR TITLE
Login system to master

### PR DESCRIPTION
**Pull request by bluo999**
A login system with 4 usernames and a task for each of them.

### CODE REVIEW

**Comment by renzhezizhi** [comment]
Where is the Dev1.0 branch?

**Comment by bluo999** [comment]
I deleted it after finishing the previous part then made this new one called "login" because I was getting errors in my local git with "Dev1.0"

**Comment by renzhezizhi** [comment]
Can you describe what kind of error you get?

**Comment by renzhezizhi** [comment]
Remember please add the description about you have done in the pull request description so the viewers/team member will know what happens.

**Comment by bluo999** [comment]
I hadn't deleted the Dev1.0 and 2.0 branches locally, so that was the problem. It's now fixed, and from now on I'll make new Dev1.0 branches.

**Pull request merged**
